targets : normal-prerequisites | order-only-prerequisites

-------------------
Automatic Variables
-------------------
$@ - The file name of the target of the rule
$< - The name of the first prerequisite
$^ - The names of all the prerequisites, with spaces between them.
$? - The names of all the prerequisites that are newer than the target, with spaces between them.
$+ - This is like '$^', but prerequisites listed more than once are duplicated in the order they were listed in the makefile.
$| - The names of all the order-only prerequisites, with spaces between them.

$(@D) - The directory part of the file name of the target, with the trailing slash removed
$(@F) - The file-within-directory part of the file name of the target.
