set nocompatible
set encoding=utf-8
set termencoding=utf-8
set fileencodings=ucs-bom,utf-8,gb18030,cp936,big5,cp932,enc-jp,enc-kr,latin-1
set fileencoding=utf-8
set fileformat=unix
language C

syntax on
set number
set expandtab
set autoindent
set backspace=2
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nowrap
set ruler
set laststatus=2
set statusline=%m%r%h%([File:%F]\ [Col:%v]\ [Lin:%l/%L/%p%%]%)
set ambiwidth=double
set wildmenu
set background=light
set noerrorbells
set visualbell t_vb=

function! BR_CFold(lnum)
    if getline(a:lnum) =~ '^{$'
        return '>1'
    endif

    if getline(a:lnum) =~ '^}$'
        return '<1'
    endif

    return '-1'
endfunction

function! BR_CSharpFold(lnum)
    if getline(a:lnum) =~ '^\( \{4\}\)\{1,2\}{$'
        return '>' . (indent(a:lnum) / &shiftwidth)
    endif

    if getline(a:lnum) =~ '^\( \{4\}\)\{1,2\}}$'
        return '<' . (indent(a:lnum) / &shiftwidth)
    endif

    return '='
endfunction

function! BR_RelativeNumberToggle()
    if (&relativenumber == 1)
        set norelativenumber
        set number
    else
        set number
        set relativenumber
    endif
endfunction

au BufNewFile,BufRead *.c,*.cc,*.cpp set foldmethod=expr foldexpr=BR_CFold(v:lnum)
au BufNewFile,BufRead *.cs set foldmethod=expr foldexpr=BR_CSharpFold(v:lnum)
au BufNewFile,BufRead Makefile,makefile,*.mak set noexpandtab
"au BufNewFile,BufRead *.html,*.xml,*.volt set tabstop=2 softtabstop=2 shiftwidth=2
"au BufRead,BufNewFile *.as set filetype=as3
"au BufRead,BufNewFile *.rs set filetype=rust
"au BufRead,BufNewFile *.volt set filetype=volt

inoremap <C-j> <C-x><C-p>
nnoremap <C-j> :call BR_RelativeNumberToggle()<CR>
nnoremap <C-k> *N:set hlsearch!<CR>

"filetype off
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
"Plugin 'Valloric/YouCompleteMe'
"call vundle#end()
"filetype on
