[theme]
name = "nord-dark"

[icons]
name = "awesome5"
[icons.overrides]
cpu = "\uf2db"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "temperature"
chip = "*-isa-*"
collapsed = false
interval = 10
format = "{average}/{max}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;M}/{mem_total;M}({mem_used_percents})"
format_swap = "{swap_used;M}/{swap_total;M}({swap_used_percents})"

[[block]]
block = "net"
format = "{speed_down;K}{speed_up;K}"

[[block]]
block = "time"
format = "%Y-%m-%d %H:%M:%S %B %A"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage:6#100} {percentage} {time}"
if_command = "test -e /sys/class/power_supply/BAT0"
