#!/bin/bash

export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS="@im=fcitx5"

~/.fehbg >/dev/null 2>&1 &
tint2 >/dev/null 2>&1 &
pasystray >/dev/null 2>&1 &
fcitx5 >/dev/null 2>&1 &
